name: Art of War
favicon: null
layout_spectrum: 0.23505
typography_spectrum: 0.5421655266545713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.04772246885113418
  lightness: 0.03335664374753833
  saturation: 0.5222562400158495
  rhythmicContrast: 0.03448320319876075
purpose: []
